### ISSUE TITLE
Removing sequences </= 200 bp from genome -- issue with preprocessReads and unequal lengths 

### ISSUE THREAD

**Issue by LAndersen0808** [fmicompbio/QuasR#25] opened 2021-03-30 17:07 UTC
I have a genome assembly (fasta.gz) consisting of 46,120 sequences ranging from 32,206,711 bp to 125 bp in length. 

I would like to remove/filter out the 33,222 (of 46,120 total) sequences that are 200 bp or less in length. A colleague pointed me in the direction of QuasR, but when I tried to filter out the shorter sequences the following error message was returned: 

 **'filename' and 'outputFilename' must have equal length.**

I then tried the following to work around this, but was unsuccessful: 

**if(length(filename) != length(outputFilename))
stop("'filename' and 'outputFilename' must have equal length.")**

I am wondering if it is possible that the error is occurring because the vectors for each individual sequence are not equal in length (?) and if this is the case, what the solution for that may be. Or, alternatively, if there is another route to take that would be better for this task. 

Thank you!

**Comment by mbstadler** [comment] 2021-03-31 06:44
Just a comment upfront: This seems to be rather a support question and not an issue with the software, so it should be addressed to the bioconductor support site (https://support.bioconductor.org/). More importantly, always provide a code example, so that I can reproduce the problem on my side, and also include the software versions that you are using (see details here: https://support.bioconductor.org/info/faq/#p1).

Guessing from the error message that you get, I am assuming that you ran the `preprocessReads` function, probably with inconsistent `filename` and `outputFilename` arguments. If your genome assembly is contained in a single file (say `"genome.fasta.gz"`), then also your output file name needs to be a single file name:
`preprocessReads(filename = "genome.fasta.gz", outputFilename = "genome_filtered.fasta.gz", minLength = 200L)`

Here is a reproducible example using the `hg19sub.fa` genome that comes with the `QuasR` package. It contains three chromosomes with lengths 40000, 10000 and 45000. I will filter out the second sequence (any sequence below the length of 12000):

```
genomefile <- system.file("extdata", "hg19sub.fa", package = "QuasR")
outfile <- "hg19sub_filtered.fa"
preprocessReads(filename = genomefile, outputFilename = outfile, minLength = 12000L)
```

which prints:
```
                 hg19sub.fa
totalSequences            3
matchTo5pAdapter          0
matchTo3pAdapter          0
tooShort                  1
tooManyN                  0
lowComplexity             0
totalPassed               2
```

Of course there are many ways how to filter a fasta file based on length. If you can fit the whole file in your computer's memory, then here is an alternative approach using the `Biostrings` package:

```
library(Biostrings)
seqs <- readDNAStringSet(genomefile)
keep <- width(seqs) >= 12000
summary(keep)
#    Mode   FALSE    TRUE 
# logical       1       2 
writeXStringSet(seqs[keep], outfile)
```

Does that answer your question?

**Comment by LAndersen0808** [comment] 2021-04-01 14:27
Thank you so much for your reply and your time. I would also like to thank you for including links to both the support site and the FAQ (very, very helpful). I used the code that you provided and the full code is attached as a text file (including traceback, session info). The primary issue at the moment seems to still be at the preprocessReads step, but is different than before:

`Error in preprocessReads(filename = genomefile, outputFilename = outfile,  : 
  unsupported file format (must be one of 'fasta' or 'fastq'): `

I also started to try the Biostrings option, but it looks like I need to unmask objects (see attached, I will have to look into this more later today). I am entirely grateful for any feedback you have for troubleshooting the above, but can/will also move this to the support site too. Thank you again for your help and direction!


[LAndersen0808-Code-1April2021.txt](https://github.com/fmicompbio/QuasR/files/6244231/LAndersen0808-Code-1April2021.txt)

**Comment by csoneson** [comment] 2021-04-03 10:30
I think the problem is this line: 

```
genomefile <- system.file("WB-Fasta-Files", "WBOrigGenome.fasta.gz", package = "QuasR")
```

This will look for the file `WBOrigGenome.fasta.gz` inside the installation folder for `QuasR` (which is where the example data is located, but your data is not there). You need to provide the actual path to your file, e.g. (assuming that you are in the same directory as the file): 

```
genomefile <- "WBOrigGenome.fasta.gz"
file.exists(genomefile)   ## Should be TRUE
```

**Comment by LAndersen0808** [comment] 2021-04-06 03:54
Hello, thank you both for your help on this. 

With everything else the same, I tried `genomefile <- "WBOrigGenome.fasta.gz"
file.exists(genomefile)   ## Should be TRUE`. This returned as TRUE, however, I ran into a new error: 
`Error in preprocessReads(filename = genomefile, outputFilename = outfile,  : 
  compressed 'fasta' input is not yet supported`

Oddly enough..I tried the following again, despite having errors returned prior, and it did the trick:

```
> library(Biostrings)
> seqs <- readDNAStringSet(genomefile)
> outfile <- "WBFilteredGenome.fasta.gz"
> keep <- width(seqs) >= 201
> summary(keep)
> #    Mode   FALSE    TRUE 
> # logical       1       2 
> writeXStringSet(seqs[keep], outfile, format="fasta", compress=TRUE)
```

Thank you both again!

**Comment by csoneson** [comment] 2021-04-06 06:45
The first error message tells you that `preprocessReads()` does not currently support compressed fasta files (so you would have to decompress it before calling this function). The `Biostrings` approach also failed previously since it couldn't find the file, so it makes sense that it works fine once the `genomefile` is correctly specified. 

It seems that this problem is solved, so I will close this issue.

**Closed by csoneson** 2021-04-06 06:45 UTC
