### ISSUE TITLE
Relative paths in the sampleFile are not recognised by qAlign when called within a netxflow run

### ISSUE THREAD

**Issue by KrebsLab** [fmicompbio/QuasR#34] opened 2022-11-15 14:48 UTC
Good afternoon,

I was wondering wether you ever tried using QuasR from within a nextflow pipeline (or snakemake or similar). For reasons not very clear to me qAlign doesn't recognise relative fq paths when called from within a nextflow run. As I'm sure you expect, the same relative paths (symlinks too) work otherwise.

Any idea why that might be the case?

Thank you very much for your support!

**Comment by monfortm** [comment] 2022-11-24 10:54
Hello, I woprk on the project with @KrebsLab 

I can confirm this is most likely a nextflow related issue, tried to reproduce with a minimal example and could not... 

You can close this issue

**Comment by monfortm** [comment] 2022-11-24 13:59
OK, I was able to reproduce. When the sample file is a symlinked file it fails. e.g.

```
lrwxrwxrwx  1 monfort gbcs   33 Nov 24 14:54 quasrSampleSheet.txt -> sample-sheet/quasrSampleSheet.txt
drwxr-xr-x  2 monfort gbcs    1 Nov 24 14:54 sample-sheet
lrwxrwxrwx  1 monfort gbcs   21 Nov 24 11:34 test1.fq.gz
lrwxrwxrwx  1 monfort gbcs   21 Nov 24 11:34 test2.fq.gz
```

with a sample sheet as so

```
FileName1	FileName2	SampleName
test1.fq.gz	test2.fq.gz	test
```

Which means the fastq files are most likely expected to be in the same directory as the sample sheet AFTER the sample sheet path was resolved. IMO, the current working directory should be used, not the sample sheet path.

**Comment by monfortm** [comment] 2022-11-24 14:18
In the meantime, with nextflow, staging files as a copy (process' `stageInMode "copy"`, or resolving the symlink with `cp --remove-destination $(readlink quasrSampleSheet.txt) quasrSampleSheet.txt`) solves the issue

**Comment by mbstadler** [comment] 2022-11-27 15:46
Great, I am glad you found a way to make it work properly with `NextFlow`.

You are correct that the relative paths in the sample sheet are interpreted relative to the location of the sample sheet, not the current working directly or the location of a symbolic link to the sample sheet. This is expected behaviour and documented, for example in the `QuasR` vignette (https://fmicompbio.github.io/QuasR/articles/QuasR.html): "... The paths can be absolute or relative to the location of the sample file."

I will close the issue for now as there seems to be a workable solution and the behaviour is according to the documentation. Feel free to re-open it in case you have any further need.

**Closed by mbstadler** 2022-11-27 15:46 UTC
