### ISSUE TITLE
Bug during SAM to BAM convertion

### ISSUE THREAD

**Issue by Mathias-Boulanger** [fmicompbio/QuasR#42] opened 2023-10-10 20:58 UTC
Dear QuasR team,

I am facing a problem during SAM to BAM convertion. I am using QuasR to align bisulfite converted DNA on the _Drosophila_ dm6 genome. 

```
alignment files missing - need to:
    create 2 genomic alignment(s)
Testing the compute nodes...OK
Loading QuasR on the compute nodes...preparing to run on 24 nodes...done
Available cores:
XXX.cluster.XXX.de: 24
Performing genomic alignments for 2 samples. See progress in the log file:
/PATH/TO/Dmelanogaster.dm6/QuasR_log_2face669bf633e.txt
[E::hts_open_format] Failed to open file /scratch/boulanger/tmp/RtmplFAyqS/samToBam_2fad632254ed2/chrUn_DS484229v1.sam
Error in checkForRemoteErrors(val) : 
  one node produced an error: Error on XXX.cluster.XXX.de processing sample /scratch/boulanger/tmp/RtmplFAyqS/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz2fad63395893eb.fastq : failed to open SAM/BAM file
  file: '/scratch/boulanger/tmp/RtmplFAyqS/samToBam_2fad632254ed2/chrUn_DS484229v1.sam'
Calls: qAlign ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
```

Here the progress log:
```
[1] "Decompressing file on XXX.cluster.XXX.de : /PATH/TO/2023-10-07-GJFV9_emb_stg5_NMB5_23/Trimmed/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz"
[1] "Decompressing file on XXX.cluster.XXX.de : /PATH/TO/2023-10-07-GJFV9_emb_stg5_NMB5_23/Trimmed/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_2_sequence.txt.gz_val_2.fq.gz"
[1] "Executing bowtie (CtoT and GtoA) on XXX.cluster.XXX.de using 24 cores. Parameters:"
[1] "'/PATH/TO/x86_64-pc-linux-gnu/4.2.0/BSgenome.Dmelanogaster.UCSC.dm6.RbowtieCtoT/alignmentIndex/bowtieIndexCtoT' -1 '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq_readsCtoT_1_3d388665c6c65d.fastq' -2 '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq_readsCtoT_2_3d3886611d3128.fastq' --ff -e 70 -X 1000 -k 2 --best --strata --phred33-quals -S -p 24 --norc '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq.readsCtoT_genomeCtoT_3d3886536a2b21.sam'"
[1] "'/PATH/TO/x86_64-pc-linux-gnu/4.2.0/BSgenome.Dmelanogaster.UCSC.dm6.RbowtieCtoT/alignmentIndex/bowtieIndexGtoA' -1 '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq_readsCtoT_1_3d388665c6c65d.fastq' -2 '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq_readsCtoT_2_3d3886611d3128.fastq' --ff -e 70 -X 1000 -k 2 --best --strata --phred33-quals -S -p 24 --nofw '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq.readsCtoT_genomeGtoA_3d38864cf9b93f.sam'"
[1] "'/PATH/TO/x86_64-pc-linux-gnu/4.2.0/BSgenome.Dmelanogaster.UCSC.dm6.RbowtieCtoT/alignmentIndex/bowtieIndexCtoT' -2 '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq_readsRcCtoT_1_3d388652419c4.fastq' -1 '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq_readsRcCtoT_2_3d3886768a5a66.fastq' --ff -e 70 -X 1000 -k 2 --best --strata --phred33-quals -S -p 24 --norc '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq.readsRcCtoT_genomeCtoT_3d38867a644688.sam'"
[1] "'/PATH/TO/x86_64-pc-linux-gnu/4.2.0/BSgenome.Dmelanogaster.UCSC.dm6.RbowtieCtoT/alignmentIndex/bowtieIndexGtoA' -2 '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq_readsRcCtoT_1_3d388652419c4.fastq' -1 '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq_readsRcCtoT_2_3d3886768a5a66.fastq' --ff -e 70 -X 1000 -k 2 --best --strata --phred33-quals -S -p 24 --nofw '/scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq.readsRcCtoT_genomeGtoA_3d388639ec4e17.sam'"
[1] "mergeReorderMaxQueueSize 1880"
[1] "Converting sam file to sorted bam file on XXX.cluster.XXX.de : /scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq3d3886286e5f1b.sam"
[1] "Error on XXX.cluster.XXX.de processing sample /scratch/boulanger/tmp/RtmpOSr6zM/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1.fq.gz3d3886479912f7.fastq : failed to open SAM/BAM file\n  file: '/scratch/boulanger/tmp/RtmpOSr6zM/samToBam_3d388679632e6/chrUn_DS484228v1.sam'"
```
I already used QuasR in the past with this genome and it works perfectly with mm10 genome for example. I tried with fresh R/QuasR install, different R versions as well or reducing down the threading to minimum, nothing succeeded.
I don't know if this is related but the problem appeared when we upgrade our HPC server to from CentOS7 to el8 red Hat.

Do you have any idea where the problem is coming from?

Rsession:
```
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Rocky Linux 8.7 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /g/easybuild/x86_64/Rocky/8/znver2/software/FlexiBLAS/3.2.1-GCC-12.2.0/lib64/libflexiblas.so.3.2                                                           

locale:
[1] C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] QuasR_1.36.0                          Rbowtie_1.38.0
 [3] BSgenome.Dmelanogaster.UCSC.dm6_1.4.1 BSgenome_1.66.1
 [5] rtracklayer_1.58.0                    Biostrings_2.66.0
 [7] XVector_0.38.0                        GenomicRanges_1.50.2
 [9] GenomeInfoDb_1.34.6                   IRanges_2.32.0
[11] S4Vectors_0.36.1                      BiocGenerics_0.44.0
[13] optparse_1.7.3

loaded via a namespace (and not attached):
 [1] MatrixGenerics_1.10.0       Biobase_2.58.0
 [3] httr_1.4.7                  bit64_4.0.5
 [5] GenomicFiles_1.34.0         BiocFileCache_2.6.0
 [7] latticeExtra_0.6-30         blob_1.2.4
 [9] GenomeInfoDbData_1.2.9      Rsamtools_2.12.0
[11] yaml_2.3.7                  progress_1.2.2
[13] pillar_1.9.0                RSQLite_2.3.1
[15] lattice_0.20-45             glue_1.6.2
[17] digest_0.6.33               RColorBrewer_1.1-3
[19] Matrix_1.6-1.1              XML_3.99-0.14
[21] pkgconfig_2.0.3             ShortRead_1.56.1
[23] biomaRt_2.54.0              zlibbioc_1.44.0
[25] jpeg_0.1-10                 getopt_1.20.3
[27] BiocParallel_1.32.5         tibble_3.2.1
[29] KEGGREST_1.38.0             generics_0.1.3
[31] cachem_1.0.8                SummarizedExperiment_1.28.0
[33] GenomicFeatures_1.50.3      cli_3.6.1
[35] deldir_1.0-6                magrittr_2.0.3
[37] crayon_1.5.2                memoise_2.0.1
[39] fansi_1.0.5                 xml2_1.3.3
[41] hwriter_1.3.2.1             tools_4.2.2
[43] prettyunits_1.1.1           hms_1.1.3
[45] BiocIO_1.8.0                lifecycle_1.0.3
[47] matrixStats_1.0.0           stringr_1.5.0
[49] interp_1.1-3                DelayedArray_0.24.0
[51] AnnotationDbi_1.60.0        compiler_4.2.2
[53] rlang_1.1.1                 grid_4.2.2
[55] RCurl_1.98-1.12             VariantAnnotation_1.44.0
[57] rjson_0.2.21                rappdirs_0.3.3
[59] bitops_1.0-7                restfulr_0.0.15
[61] codetools_0.2-19            DBI_1.1.3
[63] curl_5.1.0                  R6_2.5.1
[65] GenomicAlignments_1.34.0    dplyr_1.1.3
[67] fastmap_1.1.1               bit_4.0.5
[69] utf8_1.2.3                  filelock_1.0.2
[71] stringi_1.7.12              Rcpp_1.0.11
[73] vctrs_0.6.3                 png_0.1-8
[75] dbplyr_2.3.4                tidyselect_1.2.0
```

**Comment by mbstadler** [comment] 2023-10-11 08:01
Dear @Mathias-Boulanger 

I think the issue is likely caused by your scratch directory running out of disk space. You could check this by processing just a subset of your sequencing data (say the first 1000 read pairs) and see if that runs through. If this is indeed the issue, try setting `cacheDir` to a path with sufficient free space. 

Let me know if that fixes the issue. 

Best wishes,
Michael

**Comment by Mathias-Boulanger** [comment] 2023-10-11 09:28
Dear @mbstadler,

Thank you for your prompt reply!
This is what I thought at the beginning but we have constantly ~300To available on our `scratch` dir. I thought it was coming from the server I/O settings  about the open file limit because I got 'too much open file' time to time... 

I tried with a subset of 1k reads but I got still the same error:
```
[E::hts_open_format] Failed to open file /scratch/boulanger/tmp/Rtmp6YhDSR/samToBam_36c0a720786d54/chrUn_DS484229v1.sam
Error in checkForRemoteErrors(val) : 
  one node produced an error: Error on smem04-4.cluster.embl.de processing sample /scratch/boulanger/tmp/Rtmp6YhDSR/GJFV9_Drosophila_SMF_23s002742-1-1_Li_lane1NMB5_1_sequence.txt.gz_val_1_test.fq.gz36c0a74053e357.fastq : failed to open SAM/BAM file
  file: '/scratch/boulanger/tmp/Rtmp6YhDSR/samToBam_36c0a720786d54/chrUn_DS484229v1.sam'
Calls: qAlign ... clusterApply -> staticClusterApply -> checkForRemoteErrors
```

What is strange is everything is running smoothly when using another genome like 'BSgenome.Mmusculus.UCSC.mm10' or 'BSgenome.Hsapiens.UCSC.hg38' using the full dataset or the subset.

Could it be related to the high number of small contigs of the _Drosophila_ genome (1 869) compared to the other genome (hg38=473 and mm10=162) and the queuing system?

Maybe relevant : https://github.com/samtools/samtools/issues/603
There is only 1015 tmp sam files in the temporary folder while 1869 are expected, isn't it?

UPDATE: 
The alignment succeeded when I used only 3 cores. Therefore, I think the problem may come from `samToSortedBamParallel()` function in createAlignments-functions.R
It took ~1:30 hrs when usually only 10min is required but at least I can continue...

**Comment by mbstadler** [comment] 2023-10-11 15:20
Thanks for checking with 1k reads - I think we can rule out the issue stemming from running out of free space. I think you may have identified the issue with your UPDATE and with: ```... the server I/O settings about the open file limit because I got 'too much open file'```.

The sam to bam file conversion step will open at least two files per chromosome per parallel thread, and if you run out of file handles, the error message would be similar as if you run out of disk space. One work around that you already found is to run with less threads, alternatively you would increase the limit on your file handles, which may need to be done by your system administrator. If it is the number of available file handles, there is little that can be done about it within `R` or `QuasR`.

**Comment by mbstadler** [comment] 2023-10-13 07:57
I will close the issue for now. Please feel free to reopen it if needed.

**Closed as completed by mbstadler** 2023-10-13 07:57 UTC
